<a href="https://colab.research.google.com/github/kc1code/Machine-learning-concepts/blob/main/Matrix_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

creating matrix using numpy

In [ ]:
matrix_1 = np.array([[2, 3], [6, 7]])
print(matrix_1)

[[2 3]
 [6 7]]


In [ ]:
matrix_1.shape

(2, 2)

In [ ]:
matrix_2 = np.array([[10, 20, 30], [44, 63, 45], [20, 53, 89]])
print(matrix_2)

[[10 20 30]
 [44 63 45]
 [20 53 89]]


In [ ]:
matrix_2.shape

(3, 3)

creating matrices with random values

In [ ]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)

[[0.23632443 0.77231493 0.07310315]
 [0.16533855 0.56127038 0.34611016]
 [0.90460717 0.82566254 0.45644531]]


creating matrix with random integer

In [ ]:
random_int_matrix = np.random.randint(100, size=(4, 5))      #100 heare define that how much values it can take ...here up to 100 any random no can be taken
print(random_int_matrix)

[[31 56 31 79  8]
 [98 66 82 97 34]
 [60 61 49 87 47]
 [ 6 79 65 63 88]]


matrix with all values as 1

In [ ]:
matrix_3 = np.ones((5,6))
print(matrix_3)

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]]


In [ ]:
matrix_3 = np.ones((2,3), dtype=int)
print(matrix_3)

[[1 1 1]
 [1 1 1]]


Null matrix or zero matrix

In [ ]:
null_matrix = np.zeros((3,4))
print(null_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


Identity matrix

In [ ]:
identity_matrix = np.eye(2,3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]]


transpose of a matrix

In [ ]:
b = np.random.randint(100, size=(3, 4))
print(b)

[[35 59 92 63]
 [72 89 94 87]
 [84 14  0 81]]


In [ ]:
transpose_of_b = np.transpose(b)
print(transpose_of_b)

[[35 72 84]
 [59 89 14]
 [92 94  0]
 [63 87 81]]


Importing numpy library

In [1]:
import numpy as np

**Matrix** **Addition**

two martix can only be added if they have same shape

In [2]:
#creating two matrices
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [3]:
print(A)

[[2 3]
 [4 5]]


In [4]:
print(B)

[[6 7]
 [8 9]]


In [5]:
A.shape

(2, 2)

In [6]:
B.shape

(2, 2)

Adding the matrices

In [7]:
sum = A+B
print(sum)

[[ 8 10]
 [12 14]]


In [15]:
#creating two values with random numbers
matrix_1 = np.random.randint(50, size=(3,4))
matrix_2 = np.random.randint(50, size=(3,4))
print(matrix_1)

[[ 4 17 16 44]
 [15  4 48 12]
 [ 4 27 21 42]]


In [16]:
print(matrix_2)

[[39 33 46 46]
 [36 18 39  1]
 [45 34 21  6]]


In [17]:
sum = matrix_1 + matrix_2
print(sum)

[[43 50 62 90]
 [51 22 87 13]
 [49 61 42 48]]


In [18]:
#creating two values with random numbers
matrix_1 = np.random.randint(50, size=(3,3))
matrix_4 = np.random.randint(50, size=(3,4))

In [19]:
sum = np.add(matrix_1, matrix_4)
print(sum)

ValueError: operands could not be broadcast together with shapes (3,3) (3,4) 

we get this error beacuse they don't have same shape

**Matrix Substraction**

In [20]:
#creating two matrices
A = np.array([[2, 3], [4, 5]])
B = np.array([[6, 7], [8, 9]])

In [21]:
diff = A - B
print(diff)

[[-4 -4]
 [-4 -4]]


In [22]:
#creating two values with random numbers
matrix_1 = np.random.randint(50, size=(3,3))
matrix_2 = np.random.randint(50, size=(3,3))
print(matrix_1)

[[35  8  1]
 [21 45 13]
 [23 13 44]]


In [23]:
print(matrix_2)

[[48  9 41]
 [32 14 33]
 [ 1 24 28]]


In [25]:
#difference = matrix_1 - matrix_2
#print(difference)
diff = np.subtract(matrix_1, matrix_2)
print(diff)

[[-13  -1 -40]
 [-11  31 -20]
 [ 22 -11  16]]


**Matrix Multiplication**

In [26]:
x = 4
y = np.random.randint(20, size=(2,2))
z = x * y
print(z)

[[20 64]
 [24 48]]


In [27]:
product = np.multiply(x, y)
print(product)

[[20 64]
 [24 48]]


In [28]:
#creating two values with random numbers
matrix_1 = np.random.randint(50, size=(3,3))
matrix_2 = np.random.randint(50, size=(3,4))
print(matrix_1)

[[36 18 39]
 [24 23  5]
 [48 45 35]]


In [29]:
print(matrix_2)

[[42 15  7 49]
 [14 38  6 13]
 [41 16 25 46]]


In [30]:
product = np.dot(matrix_1, matrix_2)
print(product)

[[3363 1848 1335 3792]
 [1535 1314  431 1705]
 [4081 2990 1481 4547]]


In [31]:
product.shape

(3, 4)

In [32]:
#creating two values with random numbers
matrix_1 = np.random.randint(50, size=(3,3))
matrix_2 = np.random.randint(50, size=(4,4))

In [33]:
product = np.dot(matrix_1, matrix_2)
print(product)

ValueError: shapes (3,3) and (4,4) not aligned: 3 (dim 1) != 4 (dim 0)

we get this error because the no of columns in the first matrix should be equal to the no of rows in the second matrix but here it is not